### ISSUE TITLE
[BUG] Issue generating css from scss

### ISSUE THREAD

**Issue by robwirving** [mattstratton/castanet#211]
*** Just before posting I took a closer look at your contributing guidelines and saw a reference to custom-variables.scss. I don't see this file in the castanet repo however, perhaps it's not checked in? ***

I was attempting to create my own 'purple' theme similar to the provided grey, orange and blue themes. I copy/pasted the blue & blue_variables scss files into new purple ones, modified some of the colors, then ran node-sass against them. node-sass complains with an error that '$gray-lighter' is an undefined variable.

I searched for gray-lighter in the repo and found that that name only appears in the {color}_variables.scss files; where it is used to set the pagination-hover-bg, and another variable $gray-light is used to set the pagination-disabled-color. 

I then tested running node-sass against some of the existing colors and found that they complain with the same error. I then tried to set some grey colors to gray-light and gray-lighter variables. After doing this node-sass was able to successfully create css output. However when the Hugo website runs with these modified css files the Navigation Bar disappears.

I maybe using the wrong/different tool to generate my css. If that's the case I'd appreciate some help/docs about how to generate a new or modified color style to use.

**Comment by mattstratton** [comment]
This is a good question! Let me do some digging and figure out what's up with `custom-variables.scss`

**Comment by mattstratton** [comment]
Aha! That's a documentation bug. I used to have `custom-variables.scss`, but it's been replaced with the different color combo files, i.e. `blue-variables.scss`, etc. I'll update the contributing files.

I used to use [CodeKit](https://codekitapp.com/) for generating CSS from the SCSS, but since that's not a free tool, I should myself move to something that is more accessible for others, so that I can make sure it works.

**Comment by robwirving** [comment]
Ah okay. Thanks for looking into this.

**Comment by mattstratton** [comment]
I know I closed this issue, but wanted @robwirving to have some details on a few things (especially an interesting fix for making your own colors and such).

So long story short, you can now generate the CSS files from the SCSS files that are in `static/scss` inside this directory. But; if you want to have your own special theme (i.e., instead of "orange" or "blue", you want "my-cool-podcast" with your own variable colors), it's possible. I creatd a gist at https://gist.github.com/mattstratton/1787e406cd1144f9866c55b45aad9a8d that should help!
