### ISSUE TITLE
show future episodes

### ISSUE THREAD

**Issue by paulczar** [mattstratton/castanet#257]
We want to schedule future episodes have have them visible.

My thought was to have a configurable number of future episodes listed in the main episodes page, and then a seperate future episodes page to show them all.

Super useful for shows that are scheduled on the regular and people are organized well enough to actually update internet websites beforehand.

**Comment by chrisreddington** [comment]
+1 for this request :)

**Comment by mattstratton** [comment]
I'm just slightly thinking this through (finally), because, of course, now it's relevant to me so I'll work on it 😄 

There are two ways I could think of this:

1) It is based solely upon date; if the date of the episode is in the future, then it would be "upcoming". The thing about this is that you would have to do a manual build to make it change, even if the date passed (because static site)
2) Have a new frontmatter field that is `upcoming = true` or something like that. It would support having the dates be in the future, but the frontmatter has to be set for it to show up as "upcoming" and also it would be a filter on both the main views as well as the "upcoming" view.

I can probably work on this today or tomorrow and have a PR to demo soon!

**Comment by chrisreddington** [comment]
Thanks @mattstratton - more than happy to act as a tester on my own site if it helps too! (www.cloudwithchris.com)

I like the idea of upcoming = true as a frontmatter, as you may have certain dates in the future as "not ready for publishing", so it gives the ability to have a working area of items. In theory, that could be managed in a separate branch, but just in case.. :)

**Comment by mattstratton** [comment]
yeah, that also seems the least impactful to people who don't want to use the feature.

I just did a quick check to test the ability to exclude the "upcoming" posts, so I think this should be pretty straightforward. the page for upcoming will take a slight bit more effort but nothing too huge :)

**Comment by mattstratton** [comment]
@chrisreddington I just put in PR #297 that I *think* handles all of this; if you have a few minutes to poke at it and see if it looks good to you, I'd appreciate it (you can look at the code, or just even poke at the linked deploy preview). I'm 99% sure this is good to go, but it's a big enough change that another set of eyes would be cool.

Pending a review, I'll merge this and cut a new release with it!

**Comment by chrisreddington** [comment]
@mattstratton - cheers, I made a review on the PR
