### ISSUE TITLE
[Bug] Navbar nests links and results in 404 error

### ISSUE THREAD

**Issue by Fenugreek** [mattstratton/castanet#269]
### Expected behavior
Clicking on "Guests" on the nav bar followed by "Hosts" on the nav bar should take you to 
`<baseURL>/host`

### Actual behavior
Taken to 
`<baseURL>/guest/host`
instead, resulting in a 404 error.

### Reproduction Steps
Go to my website that's running my up-to-date branch of castanet [subburam.org/podcast](https://subburam.org/podcast)
Click on 'Guests' and then 'Host' on the Navbar.

### Operating System and Version
ArchLinux

### Web Browser and Version
Firefox 74.0

### Hugo Version
0.68.3

**Comment by mattstratton** [comment]
yeah, the thing you need to do is prepend the path in the menu with a "/", like this:

https://github.com/arresteddevops/ado-hugo/blob/master/config.toml#L28

I don't remember why, but there is a reason that the root slash isn't handled by the theme (if I think about it I might remember).

I'm not going to close this issue, because I want to do some more research, but for the time being, that fix will work for you!

**Comment by Fenugreek** [comment]
Cool, thanks for providing me with a quick fix--adding the slash worked. Might just be user error on my part!

**Comment by mattstratton** [comment]
I think this can be closed!
