### ISSUE TITLE
How do I have the linkedin social param link to a company page?

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#348]
My linkedin page is like:

https://www.linkedin.com/company/mycompany/

but if i just put

<pre>
  [params.social]
...
    linkedin = "mycompany"
</pre>

Then the link it generates is https://www.linkedin.com/inmycompany/ which obviously doesn't work.

**Comment by mattstratton** [comment]
Yeah, it assumes a personal one. 

I think it would be possible to write some code where that would take either the full URL or just the short version (it needs to support the "short version" because backwards compatibility).

Now that I think of it, all the places social URLs exist they should support putting in the full URL and not just the profile name; I'll rename and relabel this issue to track that work

**Comment by cpswan** [comment]
I was just about to ask for LinkedIn groups support e.g.

https://www.linkedin.com/groups/1234567

But seeing this request, it seems that should probably be part of the same enhancement.

**Comment by mattstratton** [comment]
Yeah, I'll try to get #350 taken care of shortly which will handle all of this :)

**Comment by mattstratton** [comment]
Fixed in #368
