### ISSUE TITLE
[BUG] - Episode Layouts are wrong on home page

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#351]
**Describe the bug**
For some reason the indentation is different between my two episodes.  I'm not sure what I'm doing wrong there.

<img width="1058" alt="Screen Shot 2021-04-07 at 10 57 03 AM" src="https://user-images.githubusercontent.com/1863749/113888198-1d719580-9790-11eb-9b61-601c4185577c.png">

**Comment by mattstratton** [comment]
Do you have a link to your public repo? I can take a look.

**Comment by ctindel** [comment]
https://github.com/ctindel/softwareinblue.com

**Comment by ctindel** [comment]
Would be nice to not have that CWC0 text there I'm not sure what that's all about either :)

**Comment by mattstratton** [comment]
that is coming from the episode number style/prefix; it's optional

https://github.com/ctindel/softwareinblue.com/blob/fb91e5b42e05deffdb147f67bf3b0a527273e62a/config.toml#L47-L48

take a look at https://github.com/mattstratton/castanet/blob/main/REFERENCE.md#general-parameters to see how that works; you can just remove those two lines if you don't want a prefix for the episode numbers.

**Comment by mattstratton** [comment]
aha I found the bug in the theme; for some reason the div for the first row is `<div class = "col-md-3">` and for the rest of them it is `<div class = "col-md-4">`

This isn't noticeable if the first episode at the top of the hero has a banner which is why I didn't notice it. I'll get this fixed soon (I'm going to try to bundle a few fixes so it should be in a day or so at the latest)
