### ISSUE TITLE
[BUG] - Guest Page isn't generating new guests

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#363]
**Describe the bug**
I added my second episode and for some reason the new guests are not being added to the guests page (even though they are added to the episode page).

All 3 of these files have type set to guest:

https://github.com/ctindel/softwareinblue.com/tree/main/content/guest

But the guest links for kyle and nick don't work:

https://softwareinblue.com/episode2.html

And they aren't listed on the guest page:

https://softwareinblue.com/guest

Is there something I'm doing wrong?  Any help would be appreciated.

**Comment by mattstratton** [comment]
you're mis-using the `guest_group` field; it means that any guest in that group should be considered the same guest.

Since you set `guest_group = "guests"` on all of them, it says they are all Gary :)

Check out https://github.com/mattstratton/castanet/blob/main/REFERENCE.md#guest-pages for a little more detail.

Anyway, remove that field from those guests and you should be fine.

**Comment by ctindel** [comment]
@mattstratton So i removed the guest_group from all the guest pages and now when I run locally it the guest page url doesn't even show anything its just blank.

I also tried setting the guest group to be a different name in each one (gary, kyle, nick) and that didn't change anything either.

I can't figure out what I'm doing wrong here.

**Comment by mattstratton** [comment]
I had the same issue when I tried to reproduce this locally; the uglyUrls is likely the cause (when I removed that it worked).

I saw your note you need it for cloudflare; I'm not quite sure why the theme wouldn't be working with uglyUrls but I know there are a lot of places where we directly path to things so that could be a contributing factor.

**Comment by ctindel** [comment]
Yeah you're right, I turned off the uglyUrls feature in config.toml and it started working.  It seems like something in the theme is broken when that option is enabled.

Thanks for pointing that out, I never would have tried that.
